### ISSUE TITLE
Add integrations for other nearest neighbor search tools

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/systems#10]
Libraries:
- [x] [Faiss](https://github.com/facebookresearch/faiss)
- [ ] cuML
- [ ] Annoy

Vector search platforms:
- [ ] [Milvus](https://milvus.io/) (once it has more solid GPU support?)
- [ ] [Vald](https://vald.vdaas.org/)
- [ ] [Vespa](http://vespa.ai/)?
- [ ] [Pinecone](https://www.pinecone.io/)?
- [ ] [Qdrant](https://github.com/qdrant/qdrant)
