### ISSUE TITLE
Make it possible to use operators for serving or batch

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/systems#13]
- [ ] Add the capability to select output formats at the operator and/or ensemble level (np/cp/pandas/cudf etc)
- [ ] Adjust the operators as needed to work with pandas/cudf output
- [ ] Figure out how to handle operators that fetch data from external systems (provide an option to replace that with a cudf join?)
- [ ] ...
